/*Write any program that demonstrates the use of multiple catch handling, re-throwing an exception, and catching all exceptions.*/

#include<iostream>
using namespace std;

int main()
{
    return 0;
}